[project]
name = "blockchain_com_data_api"
version = "0.1.0"
authors = [
  { name="daemonchild", email="tom@daemonchild.com" },
]
description = "Python Wrapper for the BlockChain.com Data API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/daemonchild/blockchain-com-data-api-python"
Issues = "https://github.com/daemonchild/blockchain-com-data-api-python/issues"


[tool.setuptools.packages.find]
where = ["src"]
include = ["blockchain_com_data_api*"]

